version: "3"

services:
  postgresql:
    container_name: "portal_finder_postgresql"
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    container_name: "portal_finder_redis"
    image: redis:alpine
    ports:
      - 6379
    volumes:
      - ./data/redis:/data
      - ./etc/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  app: &app_base
    container_name: "portal_finder_app"
    image: jiting/portal_finder:latest
    env_file:
      - app.secret.env
      - app.local.env
    links:
      - postgresql
      - redis
    logging:
      options:
        max-size: "300m"
        max-file: "10"
    volumes:
      - ./data/storage:/home/app/storage
      - ./log:/home/app/log
      - ./tmp:/home/app/tmp
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000

  worker:
    <<: *app_base
    container_name: "portal_finder_worker"
    ports: []
    command: bundle exec rails jobs:work
